name: Build and publish

on:
  push:

jobs:
  xslt3_transformation:
    name: transform xsl to sef.json
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup nodejs
        uses: actions/setup-node@v2.5.0
        with:
          node-version: '16'
      - run: |
          npm install -g xslt3
      - run: |
          for file in xsl/template_imports_sef_json/*.xsl; do
            filename=$(echo $file | sed -e "s_.xsl__g")
            xslt3 -xsl:$file -export:$filename.sef.json -nogo
            echo "$filename.sef.json created"
          done
          echo "all files created"
      - name: pushing files to repository
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: adding sef.json files to repository
          branch: master
          skip_dirty_check: true    
          skip_fetch: true
      - name: docker build
        run: docker image build -t acdhch/tei2arche .
      - name: docker push
        run: |
          docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}" 
          docker push acdhch/tei2arche   
