name: Build and publish

on:
  push:

jobs:
  publish:
    name: publish data in gh-pages
    runs-on: ubuntu-latest
    steps:
      - name: Perfom Checkout
        uses: actions/checkout@v2
      - name: setup nodejs
        uses: actions/setup-node@v2.5.0
        with:
          node-version: '16'
      - run: |
          npm install -g xslt3
      - run: |
          for file in xsl/template_imports_sef_json/*.xsl; do
            filename=$(echo $file | sed -e "s_.xsl__g")
            xslt3 -xsl:$file -export:$filename.sef.json -nogo
            echo "$filename.sef.json created"
          done
          echo "all files created"
      - name: pushing files to repository
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: adding sef.json files to repository
          branch: master
          skip_dirty_check: true    
          skip_fetch: true
      - name: process data
        run: |
          mkdir -p ./html
          cp index.html ./html/index.html
          cp -r ./static ./html/static
          cp -r ./tei ./html/tei
          cp -r ./xsl ./html/xsl
          find ./html/xsl/ -maxdepth 1 -type f -name "*.xsl" -print0 | xargs -0 sed -i -e 's@<xsl:import href="@<xsl:import href="https://acdh-oeaw.github.io/tei2arche/xsl/@g'
          find ./html/xsl/template_imports/ -maxdepth 1 -type f -name "*.xsl" -print0 | xargs -0 sed -i -e 's@<xsl:import href="@<xsl:import href="https://acdh-oeaw.github.io/tei2arche/xsl/template_imports/@g'
          find ./html/xsl/ -type f -name "*.xsl"  -print0 | xargs -0 sed -i -e 's@href="../static/@href="https://acdh-oeaw.github.io/tei2arche/static/@g'
          find ./html/xsl/ -type f -name "*.xsl"  -print0 | xargs -0 sed -i -e 's@<script type="text/javascript" src="../@<script type="text/javascript" src="https://acdh-oeaw.github.io/tei2arche/@g'
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          publish_dir: ./html
