name: Build and publish

on:
  release:
    types: [published]

jobs:
  build_docker_image:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment, install xslt3 and transform xsl to sef.json
        uses: actions/setup-node@v2.5.0
        with:
          node-version: '16'
      - run: |
          npm install -g xslt3
          for file in xsl/template_imports_sef_json/*.xsl; do
            filename=$(echo $file | sed -e "s_.xsl__g")
            xslt3 -xsl:$file -export:$filename.sef.json -t
            echo "$filename.sef.json created"
          done
          echo "all files created"
      - uses: actions/checkout@v2
      - name: docker build
        run: docker image build -t tei2arche:latest .
      - name: docker push
        run: |
          docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}" 
          docker push tei2arche:latest
